spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    gu1-account-service: /account/**
    gu1-payment-service: /payment/**
    gu1-inventory-service: /inventory/**
    gu1-order-service: /order/**
    gu1-user-service: /user/**
    gu1-catalog-service: /catalog/**
    gu1-shopping-cart-service: /shoppingcart/**
security:
  oauth2:
    resource:
      userInfoUri: ${vcap.services.gu1-user-service.credentials.uri:http://localhost:8181}/uaa/user
  ignored: /catalog/**
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
---
spring:
  profiles: development
  application:
    name: gu1-edge-service
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    gu1-account-service: /account/**
    gu1-payment-service: /payment/**
    gu1-inventory-service: /inventory/**
    gu1-order-service: /order/**
    gu1-user-service: /user/**
    gu1-catalog-service: /catalog/**
    gu1-shopping-cart-service: /shoppingcart/**
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
  ignored: /catalog/**
---
spring:
  profiles: docker
  application:
    name: gu1-edge-service
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    gu1-account-service: /account/**
    gu1-payment-service: /payment/**
    gu1-inventory-service: /inventory/**
    gu1-order-service: /order/**
    gu1-user-service: /user/**
    gu1-catalog-service: /catalog/**
    gu1-shopping-cart-service: /shoppingcart/**
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
  ignored: /catalog/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://gu1-discovery-service:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
