spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
  application:
    name: gu1-online-store-web
zuul:
  ignored-services: '*'
  routes:
    gu1-edge-service:
      path: /api/**
      url: ${vcap.services.edge-service.credentials.uri:http://localhost:9999}
    gu1-auth-service:
      path: /user/**
      url: ${vcap.services.user-service.credentials.uri:http://localhost:8181}/uaa/user
    gu1-user-service:
      path: /users/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: ${vcap.services.gu1-user-service.credentials.uri:http://localhost:8181}/uaa/user
    client:
      accessTokenUri: ${vcap.services.gu1-user-service.credentials.uri:http://localhost:8181}/uaa/oauth/token
      userAuthorizationUri: ${vcap.services.gu1-user-service.credentials.uri:http://localhost:8181}/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
  ignored: /assets/**
---
spring:
  profiles: development
  application:
    name: gu1-online-store-web
zuul:
  ignored-services: '*'
  routes:
    gu1-edge-service:
      path: /api/**
      url: http://localhost:9999
    gu1-auth-service:
      path: /user/**
      url: http://localhost:8181/uaa/user
    gu1-user-service:
      path: /users/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      accessTokenUri: http://localhost:8181/uaa/oauth/token
      userAuthorizationUri: http://localhost:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: gu1-online-store-web
zuul:
  ignored-services: '*'
  routes:
    gu1-edge-service:
      path: /api/**
      url: http://${DOCKER_IP:192.168.99.100}:9999
    gu1-auth-service:
      path: /user/**
      url: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
    gu1-user-service:
      path: /users/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
    client:
      accessTokenUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/oauth/token
      userAuthorizationUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://gu1-discovery-service:8761/eureka/
